apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
data:
  access_key: <REPLACE_THIS_WITH_YOUR_BASE64_ENCODED_ACCESS_KEY>
  secret_key: <REPLACE_THIS_WITH_YOUR_BASE64_ENCODED_SECRET_KEY>
  host_url: <REPLACE_THIS_WITH_YOUR_BASE64_ENCODED_HOST_URL>
