apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: gpt-pvc
  annotations:
    serving.kubeflow.org/gke-accelerator: Tesla_V100
spec:
  default:
    predictor:
      parallelism: 2
      # Target concurrency of 4 active requests to each container
      minReplicas: 0 # Allow scale to zero
      maxReplicas: 4
      tensorflow:
        storageUri: pvc://model-storage/1558M/ # The PVC and path inside the PVC to the model
        runtimeVersion: "1.14.0-gpu"
        resources:
          limits:
            cpu: 1
            memory: 18Gi
            nvidia.com/gpu: 1

    transformer:
      parallelism: 12
      minReplicas: 0
      maxReplicas: 2
      custom:
        container:
          image: coreweave/gpt-transformer:0.9 # Docker image of the code found in transformer/
          name: user-container
          resources:
            limits:
              cpu: 3000m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 256Mi
