apiVersion: batch/v1
kind: Job
metadata:
  name: serialization-job
spec:
  template:
    spec:
      containers:
      - name: serialization
        image: ghcr.io/coreweave/ml-containers/tensorizer:a26e561
        args:
          - "python"
          - "-m"
          - "examples/hf_serialization"
          - "--model_type"
          - {{ .Values.serialization.model_type }}
          - {{ .Values.serialization.input_directory }}
          - {{ .Values.serialization.output_prefix }}
          - {{ default '' .Values.serialization.overwrite }}
          - {{ default '' .Values.serialization.validate }}
        env:
          ## Omitting functionality for specifying S3_ENDPOINT_URL for now
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.serialization.s3_access_key.name }}
                key: {{ .Values.serialization.s3_access_key.key }}
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.serialization.s3_secret_key.name }}
                key: {{ .Values.serialization.s3_secret_key.key }}
      restartPolicy: Never
  backoffLimit: 4
---
