apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: vs-windows10
spec:
  region: LAS1
  os:
    type: windows
  resources:
    gpu:
      type: Quadro_RTX_4000
      count: 1
    cpu:
      count: 3
    memory: 16Gi
  storage:
    root:
      size: 80Gi
      storageClassName: block-nvme-las1
      source:
        pvc:
          namespace: vd-images
          # Reference querying source image here:
          # https://docs.coreweave.com/virtual-servers/root-disk-lifecycle-management/exporting-coreweave-images-to-a-writable-pvc#identifying-source-image
          name: win10-master-20210722-las1
  # Change user name and pasword
#  users:
#    - username: SET YOUR USERNAME HERE
#      password: SET YOUR PASSWORD HERE  
  network:
    public: true
    tcp:
      ports:
        - 443
        - 60443
        - 4172
        - 3389
    udp:
      ports:
        - 4172
        - 3389
  initializeRunning: true
