apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: vs-windows-cpu
spec:
  region: LAS1
  os:
    type: windows
  resources:
    cpu:
      # Reference CPU instance label selectors here:
      # https://docs.coreweave.com/resources/resource-based-pricing#cpu-only-instance-resource-pricing
      type: amd-epyc-rome
      count: 3
    memory: 16Gi
  storage:
    root:
      size: 80Gi
      storageClassName: block-nvme-las1
      source:
        pvc:
          namespace: vd-images
          # Reference querying source image here:
          # https://docs.coreweave.com/virtual-servers/root-disk-lifecycle-management/exporting-coreweave-images-to-a-writable-pvc#identifying-source-image
          name: winserver2019std-master-20210813-las1
  # Change user name and pasword
#  users:
#    - username: SET YOUR USERNAME HERE
#      password: SET YOUR PASSWORD HERE  
  network:
    public: true
    tcp:
      ports:
        - 443
        - 60443
        - 4172
        - 3389
    udp:
      ports:
        - 4172
        - 3389
  initializeRunning: true
