apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: example-vs
  namespace: my-namespace
spec:
  region: ORD1
  os:
    type: linux
  resources:
    gpu:
      type: Quadro_RTX_4000
      count: 1
    cpu:
      count: 3
    memory: 16Gi
  storage:
    root:
      size: 40Gi
      storageClassName: block-nvme-ord1
      source:
        pvc:
          namespace: vd-images
          name: ubuntu2004-docker-master-20210323-ord1
#  users:
#    - username: SET YOUR USERNAME HERE
#      password: SET YOUR PASSWORD HERE
  network:
    public: true
    directAttachLoadBalancerIP: true
  initializeRunning: true
