---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vs-block-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: block-nvme-ord1
  volumeMode: Block
  resources:
    requests:
      storage: 20Gi
---
apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: vs-ubuntu2004-block-pvc
spec:
  region: ORD1
  os:
    type: linux
  resources:
    gpu:
      type: Quadro_RTX_4000
      count: 1
    cpu:
      count: 3
    memory: 16Gi
  storage:
    root:
      size: 40Gi
      storageClassName: block-nvme-ord1
      source:
        pvc:
          namespace: vd-images
          name: ubuntu2004-docker-master-20210323-ord1
    additionalDisks:
      - name: additional-block-volume
        spec:
          persistentVolumeClaim:
            claimName: vs-block-pvc
#  users:
#    - username: SET YOUR USERNAME HERE
#      password: SET YOUR PASSWORD HERE  
      # To use key-based authentication replace and uncomment ssh-rsa below with your public ssh key
      # sshpublickey: |
      #  ssh-rsa AAAAB3NzaC1yc2EAAAA ... user@hostname
  network:
    public: true
    tcp:
      ports:
        - 22
  cloudInit: |
    # Write a simple script
    write_files:
    - content: |
        #!/bin/bash
        echo "Hello world!"
      path: /home/myuser/script.sh
      permissions: '0744'
      owner: myuser:myuser
    # Update packages
    package_update: true
    # Install packages
    packages:
      - curl
      - git
    # Run additional commands
    runcmd:
      - [df, -h]
      - [git, version]
      - [curl, --version ]
      - [bash, /home/myuser/script.sh]
  initializeRunning: true
