apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: vs-ubuntu2004-direct-lb
spec:
  region: ORD1
  os:
    type: linux
  resources:
    gpu:
      type: Quadro_RTX_4000
      count: 1
    cpu:
      count: 3
    memory: 16Gi
  storage:
    root:
      size: 40Gi
      storageClassName: block-nvme-ord1
      source:
        pvc:
          namespace: vd-images
          name: ubuntu2004-docker-master-20210323-ord1
  # Change user name and pasword
  # User is on the sudoers list
  users:
    - username: myuser
      password: password
  network:
    public: true
    directAttachLoadBalancerIP: true
  initializeRunning: true
