apiVersion: batch/v1
kind: Job
metadata:
  name: bloom-176b
spec:
  template:
    spec:
      containers:
      - name: kserve-container
        image: harubaru1/bloom-176b:4
        command:
          - "python3"
          - "/workspace/bloom.py"
        env:
          - name: MODEL_PATH
            value: "/mnt/pvc/bloom"
          - name: MAX_LENGTH
            value: "500"
        resources:
          requests:
            cpu: 12
            memory: 64Gi
            nvidia.com/gpu: 8
          limits:
            cpu: 12
            memory: 64Gi
            nvidia.com/gpu: 8
        volumeMounts:
          - name: model-cache
            mountPath: /mnt/pvc
        resources:
          requests:
            cpu: 32
            memory: 512Gi
            nvidia.com/gpu: 8
          limits:
            cpu: 32
            memory: 512Gi 
            nvidia.com/gpu: 8
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values: 
                - LGA1
              - key: gpu.nvidia.com/class
                operator: In
                values:
                - A100_NVLINK_80GB
      restartPolicy: Never
  backoffLimit: 2
