apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microsoft-bloom-deepspeed-inference-fp16
spec:
  storageClassName: shared-nvme-las1
  accessModes:
    - ReadWriteMany
  resources:
    requests:   
      storage: 350Gi
