FROM python:3.12.0a5-alpine3.16
RUN mkdir /app
ADD downloader/ /app/
WORKDIR /app
RUN pip3 install --no-cache-dir --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt
CMD ["python3", "/app/download.py"]
