apiVersion: batch/v1
kind: Job
metadata:
  name: dalle-mini-download
spec:
  template:
    spec:
      containers:
      - name: model-downloader
        image: tweldoncw/model-downloader:1
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
          #- 'python3 download.py dalle-mini/dalle-mega /mnt/pvc'
          - 'python3 download.py dalle-mini/dalle-mini /mnt/pvc'
        volumeMounts:
          - name: model-cache
            mountPath: /mnt/pvc
        resources:
          requests:
            cpu: 1
            memory: 4Gi 
          limits:
            cpu: 1
            memory: 4Gi 
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: dalle-mini-model-cache
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values: 
                - ORD1
      restartPolicy: Never
  backoffLimit: 2
