apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-j-6b-model-cache
spec:
  storageClassName: shared-nvme-ord1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "30Gi"