apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: gpt-j-6b-deepspeed
spec:
  predictor:
    containerConcurrency: 1
    minReplicas: 1
    maxReplicas: 1 
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: gpu.nvidia.com/class
              operator: In
              values:
              - RTX_A5000
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - ORD1 
    containers:
      - name: kserve-container
        image: tweldoncw/gpt-j-6b-deepspeed:3
        env:
          - name: STORAGE_URI # Kserve mounts the PVC at /mnt/models/
            value: pvc://gpt-j-6b-model-cache/
        resources:
          requests:
            cpu: 6
            memory: 48Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 6
            memory: 48Gi
            nvidia.com/gpu: 1
