apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: gpt-j-b6-deepspeed
spec:
  predictor:
    containerConcurrency: 1
    minReplicas: 1
    maxReplicas: 1 
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: gpu.nvidia.com/class
              operator: In
              values:
              - RTX_A6000
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - ORD1 
    containers:
      - name: kserve-container
        image: tweldoncw/gpt-j-6b-deepspeed:2
        command:
          - "python3"
          - "/app/service.py"
        env:
          - name: MODEL_ID
            value: "EleutherAI/gpt-j-6B"
          - name: MODEL_PATH
            value: "/mnt/models"
          - name: STORAGE_URI # Kserve mounts the PVC at /mnt/models/
            value: pvc://gpt-j-6b-model-cache/
            # The following env vars are the default model parameters, which can be changed as needed. 
          - name: MIN_LENGTH
            value: "1"
          - name: MAX_LENGTH
            value: "1000"
          - name: TOP_K
            value: "50"
          - name: TOP_P
            value: "1.0"
          - name: TEMPERATURE
            value: "1.0" 
          - name: REPEITION_PENALTY
            value: "1.5"
        resources:
          requests:
            cpu: 6
            memory: 48Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 6
            memory: 48Gi
            nvidia.com/gpu: 1
