apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-model-cache
spec:
  storageClassName: shared-nvme-ord1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"