FROM python:3.9
RUN mkdir /app
ADD serializer/ /app/
WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN git clone https://github.com/coreweave/tensorizer && \
    cd tensorizer && \
    git checkout 35381e3812ba342991d30b71ce257503622ae828 && \
    cd .. && \
    mv tensorizer/tensorizer.py . && \
    rm -rf tensorizer
CMD ["python3", "/app/serialize.py"]