FROM python:3.9

ENV tenzorizer_commit=35381e3812ba342991d30b71ce257503622ae828

RUN mkdir /app
ADD serializer/ /app/
WORKDIR /app

RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

CMD ["python3", "/app/serialize.py"]