apiVersion: v1
kind: Pod
metadata:
  name: sleeper-pod-pvc-3
spec:
  containers:
    - name: sleeper-pod-pvc-container
      image: rtalaricw/gptj_ft:22.05
      volumeMounts:
      - mountPath: "/mnt/pvc"
        name: cache
      command:
        - sleep
        - infinity
  volumes:
    - name: cache
      persistentVolumeClaim:
        claimName: model-storage
