apiVersion: batch/v1
kind: Job
metadata:
  name: clone-to-file
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: clone
    spec:
      nodeSelector:
        node.coreweave.cloud/class: cpu
        ethernet.coreweave.cloud/speed: 10G
        topology.kubernetes.io/region: ORD1
        cpu.coreweave.cloud/family: epyc
      containers:
      - name: rsync
        image: ubuntu:latest
        command: ["bash", "-c", "apt update;DEBIAN_FRONTEND=noninteractive apt install -y qemu-utils; dd conv=sparse bs=4M if=/dev/xvda of=/tmp/disk.img;qemu-img convert -f raw -O qcow2 /tmp/disk.img /shared-data/disk.qcow2;rm /tmp/disk.*; echo 'Done'"]
        volumeDevices:
        - name: source
          devicePath: /dev/xvda
        volumeMounts:
        - mountPath: /shared-data
          name: shared-data
      restartPolicy: OnFailure
      volumes:
      - name: source
        persistentVolumeClaim:
          claimName: winserver2019std-clone-20210701-ord1
          readOnly: true
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data
      tolerations:
      - key: node.coreweave.cloud/hypervisor
        operator: Exists
      - key: is_cpu_compute
        operator: Exists