apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
  name: ubuntu-cloudimg
  namespace: tenant-<tenant>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: block-nvme-ord1
  volumeMode: Block