apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: packer-worker
  namespace: tenant-<tenant>
spec:
  region: ORD1
  os:
    type: linux
  resources:
    cpu:
      type: amd-epyc-rome
      count: 8
    memory: 32Gi
  storage:
    root:
      size: 256Gi
      storageClassName: block-nvme-ord1
      source:
        pvc:
          namespace: vd-images
          name: ubuntu2004-docker-master-20210629-ord1
    additionalDisks:
    - name: winsvr2019std
      spec:
        persistentVolumeClaim:
          claimName: winserver2019std-clone-20210701-ord1
  users:
    - username: <username>
      password: <password>
  network:
    public: true
    tcp:
      ports:
        - 22
  initializeRunning: true