#!/usr/bin/env bash

# Author: Marcin Gucki 
# https://github.com/coreweave/ml-images/blob/master/huggingface/download_huggingface.sh

set -ex

if [[ $# -ne 2 ]]; then
    echo "\
    Invalid number of arguments 
      Usage: ./download_huggingface.sh <model_name> <save_path> 
          - model_name  - model name to download e.g. NovelAI/genji-python-6b 
          - save_path  - base directory where the model is saved, e.g. /mnt/pvc 
          - concurrency(optional) - the number of parallel workers to download with, default: 10"
    exit 1
fi

MODEL_NAME=$1
SAVE_PATH=$2

# If a third argument is provided treat it as the desired concurrency
DEFAULT_CONCURRENCY=10
CONCURRENCY="${3:-$DEFAULT_CONCURRENCY}"

BLOBSTORE_PREFIX="inference"
PATH=${PATH}:"${CURRENT_DIR}/scripts/bin"

echo "SAVE_PATH: ${SAVE_PATH}"
echo "MODEL_NAME: ${MODEL_NAME}"

mkdir -pv "${SAVE_PATH}/${MODEL_NAME}"

function  download {
  echo "Downloading model ${MODEL_NAME} into ${SAVE_PATH}"
  pushd "${SAVE_PATH}"
  mkdir -p "${MODEL_NAME}"
  pushd "${MODEL_NAME}"
  curl --insecure "http://blobstore.s3.ord1.coreweave.com/inference/${MODEL_NAME}/files.txt" | awk '{print $4}' |  xargs -I {} echo cp {} $SAVE_PATH/$MODEL_NAME/ >> /tmp/file_list_$MODEL_NAME 
  s5cmd  --numworkers $CONCURRENCY --no-sign-request --endpoint-url http://s3.ord1.coreweave.com run /tmp/file_list_$MODEL_NAME 
  rm /tmp/file_list_$MODEL_NAME 
}

function set_ready {
  echo "Save .ready.txt in ${SAVE_PATH}/${MODEL_NAME}"
  pushd "${SAVE_PATH}/${MODEL_NAME}"
  touch ".ready.txt"
  tree
  popd
}

date
download
set_ready
date

exit 0
