apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
spec:
  storageClassName: shared-nvme-ord1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 350Gi


