apiVersion: batch/v1
kind: Job
metadata:
  name: bloom-175b-download
spec:
  template:
    spec:
      containers:
      - name: model-downloader
        image: tweldoncw/bloom-175b:874c8b4
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
          - 'download_model bloom /mnt/pvc'
        volumeMounts:
          - name: cache
            mountPath: /mnt/pvc
        resources:
          requests:
            cpu: 1
            memory: 4Gi 
          limits:
            cpu: 1
            memory: 4Gi 
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: model-cache
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values: 
                - ORD1
      restartPolicy: Never
  backoffLimit: 2
