apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bloom-175b-model-cache
spec:
  storageClassName: shared-nvme-las1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 350Gi


